# Generated by Django 5.1.1 on 2024-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=50)),
            ],
        ),
    ]
